[General]
background=generated/background.jpg
textColor={{colors.primary_fixed.default.hex}}
entryBackground=#11{{colors.on_primary_fixed.default.hex_stripped}}
entryBorder=#55{{colors.outline.default.hex_stripped}}
dim=0.35
m3background={{colors.background.default.hex}}
m3primary={{colors.primary.default.hex}}
m3onPrimary={{colors.on_primary.default.hex}}
m3surfaceContainerLow={{colors.surface_container_low.default.hex}}
m3onSurfaceVariant={{colors.on_surface_variant.default.hex}}
m3secondaryContainer={{colors.secondary_container.default.hex}}
m3onSecondaryContainer={{colors.on_secondary_container.default.hex}}
